"""set up tables

Revision ID: 220971b183ec
Revises: 
Create Date: 2025-02-04 05:07:04.865651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '220971b183ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('ID_COUNTRY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('COUNTRY_NAME', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CONTINENT', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('ID_COUNTRY')
    )
    op.create_table('sales',
    sa.Column('ID_ORDER', sa.String(), nullable=False),
    sa.Column('ID_PRODUCT', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ID_BUYER', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ID_SELLER', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ID_SELLER_COUNTRY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ID_BUYER_COUNTRY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('DATE_PAYMENT', sa.TIMESTAMP(), nullable=False),
    sa.Column('BRAND', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('CATEGORY', sa.Enum('CLOTHING', 'SHOES', 'ACCESSORIES', 'JEWELLERY', 'BAGS', 'DESIGN_AND_DECORATION', 'BOYS', 'GIRLS', 'SPORT_AND_LEISURE', 'HIGH_TECH', 'ART_AND_CULTURE', 'PET_ACCESSORIES', name='salecategories'), nullable=True),
    sa.Column('REVENUE', sa.Float(), nullable=False),
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID_ORDER')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('country')
    # ### end Alembic commands ###
